# Site settings
title: Xingjian Pan (潘星键)
email: xingjianpan at 163.com
description: "Xingjian Pan's Blog"
baseurl: ""
url: "http://xingjian.me"

# Build settings
markdown: kramdown
permalink: pretty

highlighter: pygments
